### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by jiangyubao** [sshaaf/quarkus-opencv-examples#2]
My GraalVM version is graalvm-ce-java11-21.0.0.2.

This project can be compiled to native and run OK on MacOS. It also can be compiled on CentOS 7.2, but it can not run OK on CentOS 7.2, and the error message is :

`java.lang.UnsatisfiedLinkError: Can't load library: /tmp/opencv_openpnp11777349376376409951/nu/pattern/opencv/linux/x86_64/libopencv_java451.so
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:104)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:273)
	at java.lang.Runtime.load0(Runtime.java:768)
	at java.lang.System.load(System.java:1835)
	at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:330)
	at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:326)
	at nu.pattern.OpenCV$LocalLoader$Holder.<clinit>(OpenCV.java:336)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at nu.pattern.OpenCV$LocalLoader.getInstance(OpenCV.java:340)
	at nu.pattern.OpenCV.loadLocally(OpenCV.java:323)
	at io.quarkiverse.opencv.runtime.OpenCVRecorder.loadOpenCVLibrary(OpenCVRecorder.java:10)
	at io.quarkus.deployment.steps.OpenCVProcessor$loadOpenCV-1726962321.deploy_0(OpenCVProcessor$loadOpenCV-1726962321.zig:67)
	at io.quarkus.deployment.steps.OpenCVProcessor$loadOpenCV-1726962321.deploy(OpenCVProcessor$loadOpenCV-1726962321.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:251)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:105)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)`

Will you know how to resolve this problem?

**Comment by jiangyubao** [comment]
My GraalVM version is
